services:
  postgres:
    image: postgres:18
    container_name: fms-postgres
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms1234
      POSTGRES_DB: fmsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fms -d fmsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
